### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by Mehtrick** [Mehtrick/bjoern#19]
- Namen von Scenarien werden noch groß geschrieben
- Wie geht man mit Rules um
- Syntax Highlighting
- Default Config
- Wenn keine Spec vorhanden ist meckert der Test. Hier lieber einfach durchlaufen und einen Hinweis ausgeben
- Standard @Before

**Comment by Kugelschieber** [comment]
Dokumentation. Vor allem dass die Specs auf .zgr enden müssen.

**Comment by Kugelschieber** [comment]
Umlaute, z.B.: `Feature: Jpa Entitäten generieren`

**Comment by Mehtrick** [comment]
> Umlaute, z.B.: `Feature: Jpa Entitäten generieren`

Kommt hiermit: [https://github.com/Mehtrick/bjoern/commit/cc953ffcd9daf456cbababe5fb0ba4c639cbe7c4](klick)

**Comment by Mehtrick** [comment]
Namen von Scenarien werden noch groß geschrieben
Wie geht man mit Rules um
Syntax Highlighting
Default Config
Wenn keine Spec vorhanden ist meckert der Test. Hier lieber einfach durchlaufen und einen Hinweis ausgeben
Standard @before

> * Namen von Scenarien werden noch groß geschrieben
> * Wie geht man mit Rules um
> * Syntax Highlighting
> * Default Config
> * Wenn keine Spec vorhanden ist meckert der Test. Hier lieber einfach durchlaufen und einen Hinweis ausgeben
> * Standard @before

- Namen wurden gefixed
- Rules sind erstmal Teil der Implementierung und nicht Teil des Frameworks. Vielleicht kommt hier noch ein späterer Nutzen hinzu
- Syntax Higlighting gibt es mit https://marketplace.visualstudio.com/items?itemName=mehtrick.bjoern
- Default Config gibt es da wo es defaults geben darf
- Wenn keine Spec vorhanden ist kommt ein Hinweis
- Before wird als Background implementiert
