### ISSUE TITLE
Pipes (|) in Parameters should be escaped for generating docs

### ISSUE THREAD

**Issue by janz04** [Mehtrick/bjoern#44]
https://github.com/Mehtrick/bjoern/blob/26609268963f5b592d32d1a1c17fc5f8068e6303/bjoern-doc/src/main/resources/asciidoc.ftlh#L10

I want to pass regexps in parameters. My regexp contains pipes.
When i generate the docs the Table is broken, because the pipe starts a new cell.
The pipe must be escaped for asciidoc with a \

**Comment by Mehtrick** [comment]
Please have a look at https://plugins.gradle.org/plugin/de.mehtrick.bjoern.gradle-plugin

Right now it is not approved by gradle, so you will get a "plugin not found". Maybe the site will show the plugin in the next days :)

**Comment by Mehtrick** [comment]
@janz04 finally its approved... https://plugins.gradle.org/plugin/de.mehtrick.bjoern.gradle-plugin
