### ISSUE TITLE
Encoding in generated Docs is not correct

### ISSUE THREAD

**Issue by janz04** [Mehtrick/bjoern#50]
https://github.com/Mehtrick/bjoern/blob/794d725bbb90c5ff803c09af3e10385fa2ecce49/src/main/java/de/mehtrick/bjoern/doc/BjoernDocGenerator.java#L38

From 1.2.6 -> 1.3.1 the Encoding for generated Docs has changed.
I have set the property to UTF-8 but still get Windows-1252.
The problem is with Umlaut

**Comment by Mehtrick** [comment]
i could reproduce it

**Comment by Mehtrick** [comment]
please have a look at the new 1.3.2 Release. The Encoding is now default to UTF-8 but can be set via the Encoding parameter

**Comment by janz04** [comment]
1.3.2 works greate.
the Encodingproblem in the docs is solved.
Thanks for fast fix and sorry for late response.
